### ISSUE TITLE
so the git dont include the h5 model?

### ISSUE THREAD

**Issue by Earlyao** [zhwuer/Chinese-Chess#2]
OSError: Unable to open file (unable to open file: name = './h5_file/new_model_v2.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
I think there is no new_model_v2.h5 as the model, so could you share the model?

**Comment by zhwuer** [comment]
Sorry for the late response, it included right now.

**Comment by Earlyao** [comment]
thanks




------------------ 原始邮件 ------------------
发件人: "zhwuer"<notifications@github.com>; 
发送时间: 2019年10月18日(星期五) 凌晨3:21
收件人: "zhwuer/Chinese-Chess"<Chinese-Chess@noreply.github.com>; 
抄送: "姚兴"<1028271706@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhwuer/Chinese-Chess] so the git dont include the h5 model? (#2)




Closed #2.
